// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAlQCxXcr2Ev-7aP3neQm4ZiGc-12XgY0',
    appId: '1:739402578429:web:7f365e0e3144d1fb7ec194',
    messagingSenderId: '739402578429',
    projectId: 'earnfromlearn-4d1a5',
    authDomain: 'earnfromlearn-4d1a5.firebaseapp.com',
    storageBucket: 'earnfromlearn-4d1a5.appspot.com',
    measurementId: 'G-H3XLR1DYKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Apsc52R8QX6sda0yJ0M5bgpCE0r50wY',
    appId: '1:739402578429:android:660315cef449d6537ec194',
    messagingSenderId: '739402578429',
    projectId: 'earnfromlearn-4d1a5',
    storageBucket: 'earnfromlearn-4d1a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsuyRwHYrg3pL2DWHLoVS6EW8jXcquiSc',
    appId: '1:739402578429:ios:60129bc2079e64ed7ec194',
    messagingSenderId: '739402578429',
    projectId: 'earnfromlearn-4d1a5',
    storageBucket: 'earnfromlearn-4d1a5.appspot.com',
    iosClientId: '739402578429-c9a95vtv9quknit09fjfqkioglj685kp.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsuyRwHYrg3pL2DWHLoVS6EW8jXcquiSc',
    appId: '1:739402578429:ios:60129bc2079e64ed7ec194',
    messagingSenderId: '739402578429',
    projectId: 'earnfromlearn-4d1a5',
    storageBucket: 'earnfromlearn-4d1a5.appspot.com',
    iosClientId: '739402578429-c9a95vtv9quknit09fjfqkioglj685kp.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
